CC      = gcc-mp-5

CFLAGS  = -Wall -pipe -msse -Ofast -D__SSE__ -U__SSE2__ -U__AVX2__
CFLAGS += -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -static-libgcc -mmacosx-version-min=10.5
CFLAGS += -fopenmp

LDFLAGS = -lm

ALL_C   = main.c alignment.c alignment_simd.c codes.c hit_map.c \
   index.c load_data.c genome_map.c reads_data.c read_quality.c \
   reference_data.c run.c seed.c stats.c util.c

all: storm-color-sse-x-gcc storm-nucleotide-sse-x-gcc

storm-color-sse-x-gcc :
	${CC} ${ALL_C} -o storm-color-sse-x-gcc ${CFLAGS} ${LDFLAGS}

storm-nucleotide-sse-x-gcc :
	${CC} -DNUCLEOTIDES ${ALL_C} -o storm-nucleotide-sse-x-gcc ${CFLAGS} ${LDFLAGS}

clean:
	rm -f *~ storm-color-sse-x-gcc storm-nucleotide-sse-x-gcc
